### ISSUE TITLE
Deprecation info

### ISSUE THREAD

**Issue by valoricDe** [dralletje/idx.macro#14]
I think it would be nice to add a small deprecation info to the start of the readme as in most environments optional chaining is the way to go now.

**Comment by dralletje** [comment]
Good point

**Comment by dralletje** [comment]
Still wondering if I should actually make it `npm deprecate` it

**Comment by valoricDe** [comment]
First I was hesitant. But after thinking about it:
Probably one is using babel with @babel/preset-env or using typescript. Both support optional chaining.
So I think deprecating it via npm is probably the easiest and best way to go.

**Comment by dralletje** [comment]
Yeah figured the same, worst case I'll un-deprecate it 🤷‍♀️

**Comment by dralletje** [comment]
![image](https://user-images.githubusercontent.com/767261/146388584-bbadbb4a-cf35-462f-b424-c8e484a5fccd.png)

Niiiiiiice
