### ISSUE TITLE
Need new npm

### ISSUE THREAD

**Issue by zentuit** [dralletje/idx.macro#2]
Kent's PR is pretty important for this project 😉 .  You need to make another npm package so we can actually use this macro!

**Comment by zentuit** [comment]
You need to also update your build directory in `master` with the new code otherwise we can't use the github npm install either.

If you want some help/advice on how to maintain npm's, shoot me a message and I'll help you out with either a PR or some tips.

**Comment by dralletje** [comment]
Oh goddangit I didn't publish the update to npm oh well hahahaha

**Comment by dralletje** [comment]
@zentuit I did update on npm now! (A major change because of the babel-macros change :D)
Thanks for the offer, I'll sure reach out when I get in trouble later on :-)
