### ISSUE TITLE
Release the `babel-plugin-macros` version

### ISSUE THREAD

**Issue by kirbycool** [dralletje/idx.macro#5]
It looks like the update from `babel-macros` to `babel-plugin-macros` hasn't made it to a release yet. The latest version on npm, `2.0.1`, still depends on `babel-macros`.
Can you release a new version with the updated dependency?

**Comment by dralletje** [comment]
Hey, thanks for letting me know :)
I finally got to publishing it (please don't look at my last commits)

**Comment by kirbycool** [comment]
Awesome! Thanks for macro.
