### ISSUE TITLE
Add TypeScript typings?

### ISSUE THREAD

**Issue by jeffreypriebe** [dralletje/idx.macro#6]
Love idx.macro for expanding otherwise noisy checks (and that I can use it within CRA with babel-plugins).

I've got TypeScript typings for idx.macro (minimal / tiny as they are). Do you want a PR here?
(This is the nicer experience for TS devs: that a package has its typing built-in, e.g. [how Redux has a single file for typing](https://github.com/reduxjs/redux/blob/master/index.d.ts).)

To be clear, I mean an `index.d.ts` file, not changing anything about the actual js code.

If not, I'll PR them into to [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped) as "community contributed" for re-use from there.

**Comment by dralletje** [comment]
Would love to see your PR :)
How did you get such an exotic type working? :o Pretty cool

**Comment by jeffreypriebe** [comment]
Not so exotic. Hopefully you don't expect _too much_ from this PR 😉.
