### ISSUE TITLE
Pull original idx typescript declaration

### ISSUE THREAD

**Issue by albertorestifo** [dralletje/idx.macro#8]
Hello!

The original facebook IDX [includes typescript delcarations](https://github.com/facebookincubator/idx/blob/master/packages/idx/src/idx.d.ts) which correctly remove nullable types from the passed object.

This is a much better typing than the one currently included in this repo. Would it be possible to pull that type declaration instead?

**Comment by dralletje** [comment]
Thanks a lot! Could you try out if it works correctly?
If you could try it by installing from github (`npm install dralletje/idx.macro`), then I can publish to npm after you confirm :)
I'm not a typescript user myself

**Comment by albertorestifo** [comment]
I tested it in my typescript project and it works perfectly.

Thanks!

**Comment by dralletje** [comment]
Thanks a lot :)
I've released it as patch release to npm (version 3.0.4)
